@startuml
class CourseEnrollment {
    + Title : string <<get>> <<set>>
    + Quota : int <<get>> <<set>>
}
class "IEnumerable`1"<T> {
}
CourseEnrollment o-> "Students<Student>" "IEnumerable`1"
@enduml
