@startuml
class UpdateDbStructureToMoreRealistic <<partial>> {
    # <<override>> Up(migrationBuilder:MigrationBuilder) : void
    # <<override>> Down(migrationBuilder:MigrationBuilder) : void
}
Migration <|-- UpdateDbStructureToMoreRealistic
@enduml
